<?php
/* 
 * Generated by CRUDigniter v2.0 Beta 
 * www.crudigniter.com
 */
 
class Client extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_model');
    } 

    /*
     * Listing of client
     */
    function index()
    {
        $data['client'] = $this->Client_model->get_all_client();
        $this->load->view('client/index',$data);
    }

    /*
     * Adding a new client
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('code','Code','required|max_length[255]');
		$this->form_validation->set_rules('display_code','Display Code','required|max_length[255]');
		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'code' => $this->input->post('code'),
				'display_code' => $this->input->post('display_code'),
				'name' => $this->input->post('name'),
				'place' => $this->input->post('place'),
				'parent_id' => $this->input->post('parent_id'),
            );
            
            $client_id = $this->Client_model->add_client($params);
            redirect('client/index');
        }
        else
        {

			$this->load->model('Client_model');
			$data['clients'] = $this->Client_model->get_all_client();
                
            $this->load->view('client/add',$data);
        }
    }  

    /*
     * Editing a client
     */
    function edit($id)
    {   
        // check if the client exists before trying to edit it
        $client = $this->Client_model->get_client($id);
        
        if(isset($client['id']))
        {
            $this->load->library('form_validation');

		$this->form_validation->set_rules('code','Code','required|max_length[255]');
		$this->form_validation->set_rules('display_code','Display Code','required|max_length[255]');
		$this->form_validation->set_rules('name','Name','required|max_length[255]');
		
		if($this->form_validation->run())     
            {   
                $params = array(
					'code' => $this->input->post('code'),
					'display_code' => $this->input->post('display_code'),
					'name' => $this->input->post('name'),
					'place' => $this->input->post('place'),
					'parent_id' => $this->input->post('parent_id'),
                );

                $this->Client_model->update_client($id,$params);            
                redirect('client/index');
            }
            else
            {   
                $data['client'] = $this->Client_model->get_client($id);
    
				$this->load->model('Client_model');
				$data['clients'] = $this->Client_model->get_all_client();

                $this->load->view('client/edit',$data);
            }
        }
        else
            show_error('The client you are trying to edit does not exist.');
    } 

    /*
     * Deleting client
     */
    function remove($id)
    {
        $client = $this->Client_model->get_client($id);

        // check if the client exists before trying to delete it
        if(isset($client['id']))
        {
            $this->Client_model->delete_client($id);
            redirect('client/index');
        }
        else
            show_error('The client you are trying to delete does not exist.');
    }
    
}
